sudo: required
services:
  - docker
language: generic
env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - # we need docker-compose, install it!
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # docker upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - # build our image app
  - docker-compose -f docker-compose.build.yml build

before_script:
  - # run the app in the background
  - docker-compose -f ./docker-compose.yml up -d
  - sleep 10 ; docker-compose logs

script:
  - # count number of running containers
  - docker-compose ps
  - NB_CONTAINERS=$(docker-compose ps | grep " Up " | wc -l)
  - test $NB_CONTAINERS = 1
